
version: '3'

services:

  PGS:
    container_name: PGS
    hostname: postgres
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=paher
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=hospital2,hoapital1
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      main:

networks:
  main:
